filebeat.modules:

- module: system
  # Syslog
  syslog:
    enabled: true

- module: auditd
  log:
    enabled: true

- module: mysql
  # Error logs
  error:
    enabled: true

- module: nginx
  # Access logs
  access:
    enabled: true

  # Error logs
  error:
    enabled: true

filebeat.prospectors:

- input_type: log
  paths:
    - /var/log/*.log

output.elasticsearch:
  enabled: true
  hosts: ["localhost:9200"]

logging.level: info
logging.metrics.enabled: true
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: capes_filebeat
  rotateeverybytes: 10485760
  keepfiles: 7
